# Generated by Django 4.2.2 on 2024-11-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_itemcarrito_unique_together_carrito_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='No disponible', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('recoger', 'Recoger en tienda')], default='domicilio', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default='Pedido sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_venta',
            field=models.CharField(default='minorista', max_length=50),
        ),
    ]
