# Generated by Django 4.2.2 on 2025-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_pedido_direccion_pedido_metodo_envio_pedido_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_venta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_envio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(choices=[('moto', 'Moto'), ('didi_auto', 'Didi Auto'), ('retiro_local', 'Retiro en el local')], default='retiro_local', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cuenta_dni', 'Cuenta DNI'), ('tarjeta', 'Tarjeta de crédito/débito'), ('mercado_pago', 'Mercado Pago')], default='efectivo', max_length=20),
        ),
    ]
