# Generated by Django 4.2.2 on 2026-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_pedido_metodo_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('recoger_tienda', 'Retirar en tienda'), ('didi_moto', 'Envío con moto (Didi)'), ('uber_moto', 'Envío con moto (Uber)'), ('didi_auto', 'Envío con auto (Didi)'), ('uber_auto', 'Envío con auto (Uber)'), ('agencia', 'Envío por Agencia')], default='domicilio', max_length=50),
        ),
    ]
